config/routes.rb
Rails.application.routes.draw do
  resources :musics
  resources :players
  resources :posts
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :musics
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :players 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:name, :author, :year)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music, local: true) do |form| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<p id="notice"><%= notice %></p>

<h1>Musics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.name %></td>
        <td><%= music.author %></td>
        <td><%= music.year %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Voltar a lista de playlists', Player %>
<%= link_to 'New Music', new_music_path %>
<% if current_user %>    

<%= link_to 'Sair', destroy_user_session_path, method: :delete %>

<% else %>

<%= link_to 'Cadastrar', new_user_registration_path %>

<%= link_to 'Entrar', new_user_session_path %>

<% end %>

app/views/musics/new.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<h1>New Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @music.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @music.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @music.year %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>

app/views/pages/home.html.erb
<style>
div.center {
        text-align: center;
}
</style>

<div class="center">
<h1>Jhonson</h1>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<% if current_user %>    

<%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<%= link_to 'Playlist', Player %>

<% else %>

<%= link_to 'Cadastrar', new_user_registration_path %>

<%= link_to 'Entrar', new_user_session_path %>

<%= link_to 'Playlist', Player %>

<% end %>
</div>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<style>
div.center {
        text-align: center;
}
</style>

<div class="center">
<h1>Editing Player</h1>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>
</div>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<style>
div.center {
        text-align: center;
}
</style>

<div class="center">
<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Tocar', Music %></td>
        <td><%= link_to 'Editar', edit_player_path(player) %></td>
        <td><%= link_to 'Deletar', player, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova playlist', new_player_path %>
<% if current_user %>    

<%= link_to 'Sair', destroy_user_session_path, method: :delete %>

<% else %>

<%= link_to 'Cadastrar', new_user_registration_path %>

<%= link_to 'Entrar', new_user_session_path %>

<% end %>
</div>

app/views/players/new.html.erb
<style>
div.center {
        text-align: center;
}
</style>

<div class="center">
<h1>New Player</h1>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Adicionar músicas', Music.new %>
<%= link_to 'Editar', edit_player_path(@player) %> |
<%= link_to 'Voltar', players_path %>
</div>